### ISSUE TITLE
Where are {train, val}/*.tsv files?

### ISSUE THREAD

**Issue by nishitkumar89** [Shivanshu-Gupta/Pytorch-POS-Tagger#7]
Where are {train, val}/*.tsv files?

**Comment by Shivanshu-Gupta** [comment]
I've described it [here](https://github.com/Shivanshu-Gupta/Pytorch-POS-Tagger#preprocessing-datasets) in the readme.

**Comment by Shivanshu-Gupta** [comment]
[here](url)

**Comment by nishitkumar89** [comment]
You perhaps need to change your README. The two inputs to paste command ought to be txt files and not tsv files
